### ISSUE TITLE
no libgstkaldionline2.so but libgstkaldinnet2onlinedecoder.so

### ISSUE THREAD

**Issue by zlinsmile** [alumae/gst-kaldi-nnet2-online#76]
ubuntu 16.04
python 2.7.12

After i finished do this:
`KALDI_ROOT=/path/of/kaldi-trunk make depend`
`KALDI_ROOT=/path/of/kaldi-trunk make`
i just got **libgstkaldinnet2onlinedecoder.so**, and there is no **'libgstkaldionline2.so'**

and then i can not do this `GST_PLUGIN_PATH=. gst-inspect-1.0 kaldinnet2onlinedecoder`
it result in 
>No such element or plugin 'kaldinnet2onlinedecoder'
but i can do this:`GST_PLUGIN_PATH=. gst-inspect-1.0 libgstkaldinnet2onlinedecoder.so`
and i got that：

> Plugin Details:
>   Name                     libgstkaldinnet2onlinedecoder.so
>   Description              Plugin for blacklisted file
>   Filename                 ./libgstkaldinnet2onlinedecoder.so
>   Version                  0.0.0
>   License                  BLACKLIST
>   Source module            BLACKLIST
>   Binary package           BLACKLIST
>   Origin URL               BLACKLIST
> 
> 
>   0 features:
> 
in my gst-kaldi-nnet2-online/src  is that:
`ls /home/2017/zhanglin/gst-kaldi-nnet2-online/src`
> Makefile             gstkaldinnet2onlinedecoder.cc  kaldimarshal.h                    simple-options-gst.cc
> gst-audio-source.cc  gstkaldinnet2onlinedecoder.h   kaldimarshal.list                 simple-options-gst.h
> gst-audio-source.h   gstkaldinnet2onlinedecoder.o   kaldimarshal.o                    simple-options-gst.o
> gst-audio-source.o   kaldimarshal.cc                **libgstkaldinnet2onlinedecoder**.so
> 

next, i continue to install kaldi-gstreamer-server

And then, i just export my GST_PLUGIN_PATH like this : GST_PLUGIN_PATH=/home/2017/zhanglin/gst-kaldi-nnet2-online/src

then when i start my master and work for online , but i got this:
> Traceback (most recent call last):
>   File "kaldigstserver/worker.py", line 419, in <module>
>     main()
>   File "kaldigstserver/worker.py", line 409, in main
>     decoder_pipeline = DecoderPipeline2(conf)
>   File "/home/2017/zhanglin/kaldi-gstreamer-server/kaldigstserver/decoder2.py", line 25, in __init__
>     self.create_pipeline(conf)
>   File "/home/2017/zhanglin/kaldi-gstreamer-server/kaldigstserver/decoder2.py", line 55, in create_pipeline
>     self.asr.set_property("use-threaded-decoder", conf["decoder"]["use-threaded-decoder"])
> AttributeError: 'NoneType' object has no attribute 'set_property'
> 

thank you so much. TT

**Comment by gilamsalem** [comment]
My folder also contains only libgstkaldinnet2onlinedecoder.so (no other so) and everything works fine.
I can run successfully "GST_PLUGIN_PATH=. gst-inspect-1.0 kaldinnet2onlinedecoder".

The worker failure is expected. When you try to load the object kaldinnet2onlinedecoder it fails and return None. After that you try to set the properties of this None object.
I don't think that you need/want to try the gstreamer server before you can successfully run the gst-inspect command.

Are you sure that the make command was successfully finished?
Do you see any errors?

**Comment by honain-derrar** [comment]
Hi, I am facing a similar issue:

using Kaldi "eb28a6ae35ccb332df1215d0bfc353cec03df76d"

The contents of my gst-kaldi-nnet2-online/src:

```-rw-rw-r--. 1 user user 3.7K Nov 28 11:56 gst-audio-source.cc
-rw-rw-r--. 1 user user 1.6K Nov 28 11:56 gst-audio-source.h
-rw-rw-r--. 1 user user  78K Nov 28 12:00 gst-audio-source.o
-rw-rw-r--. 1 user user  85K Nov 28 11:56 gstkaldinnet2onlinedecoder.cc
-rw-rw-r--. 1 user user 4.7K Nov 28 11:56 gstkaldinnet2onlinedecoder.h
-rw-rw-r--. 1 user user  21M Nov 28 12:00 gstkaldinnet2onlinedecoder.o
-rw-rw-r--. 1 user user 2.9K Nov 28 11:59 kaldimarshal.cc
-rw-rw-r--. 1 user user  490 Nov 28 11:59 kaldimarshal.h
-rw-rw-r--. 1 user user   12 Nov 28 11:56 kaldimarshal.list
-rw-rw-r--. 1 user user  14K Nov 28 12:00 kaldimarshal.o
-rwxrwxr-x. 1 user user  13M Nov 28 12:00 libgstkaldinnet2onlinedecoder.so
-rw-rw-r--. 1 user user 2.8K Nov 28 11:58 Makefile
-rw-rw-r--. 1 user user 2.4K Nov 28 11:56 simple-options-gst.cc
-rw-rw-r--. 1 user user 1.7K Nov 28 11:56 simple-options-gst.h
-rw-rw-r--. 1 user user 458K Nov 28 12:00 simple-options-gst.o```  

The contents of GST_PLUGIN_PATH
`/home/user/mnt/streaming_kaldi/kaldi/src/gst-plugin/:/home/user/mnt/streaming_kaldi/gst-kaldi-nnet2-online/src/`

` gst-inspect-1.0 kaldinnet2onlinedecoder` retruns  
 `No such element or plugin 'kaldinnet2onlinedecoder'`
